version: "3.5"

services:
  frontend:
    image: nginx:1.15-alpine
    container_name: frontend
    restart: always
    ports:
      - 3000:80

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./build:/var/www/html
